main: jdz.claimedSpawners.ClaimedSpawners
name: ClaimedSpawners
version: 1.0
author: Jonodonozym
description: Prevents spawners from being placed in unclaimed land
depend: [JBU,FactionsFramework]

permissions:
  claimedspawners.bypass:
    description: bypasses restrictions set by the plugin
    default: op